Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: topsis.Topsis
      CodeUri: /Users/abhigyanmandal/Documents/GitHub/topsis
      Runtime: java11
      Architectures:
        - arm64