version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "topsis"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l38ppv83yqya"
s3_prefix = "topsis"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
